import { ComponentFixture, TestBed } from '@angular/core/testing';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { AppLocale, LocaleService } from '../services/locale/locale.service';
import { LanguageSelectorPage } from './language-selector.page';

/**
 * LanguageSelectorPage spec.
 *
 * In short: it guarantees that the page redirects to the detected language after a short
 * delay while showing the loading view, and that, when it shows the language options, each
 * option and the contact channels behave correctly.
 *
 * Guarantees
 * - With a detected language (es, en or pt) the page calls changeLocale with that language
 *   after 1500 ms, not before, and meanwhile shows the loading view without the options.
 * - When no language is detected it shows the options ES, EN and PT in that order, hides the
 *   loading view and does not redirect on its own.
 * - Clicking an option, or releasing Enter on it, changes to its language (es, en or pt).
 * - The channel links (LinkedIn, GitHub, npm) point to the right sites and open in a new tab
 *   with rel="noopener".
 *
 * Not covered
 * - Real navigation: changeLocale is replaced by a mock so jsdom does not try to navigate.
 * - The look of the page and the content of the loading view (it has its own spec).
 * - Known gap: LocaleService.resolveStartupLocale always returns a language (it falls back to
 *   es), so in production the options are never shown and every visitor is redirected after
 *   1.5 s. The tests that show the options force an empty value to reach them.
 * - Known gap: the redirect timer is not cancelled when the component is destroyed.
 * - The uncovered branch that coverage reports on the signal field is generated by Angular
 *   (ngDevMode), it is not application code.
 */

// Same value as REDIRECT_DELAY_MS in the page.
const REDIRECT_DELAY_MS = 1500;

describe('LanguageSelectorPage', () => {
  const localeService = { changeLocale: vi.fn() };

  const createPage = (detected: string): HTMLElement => {
    // The real method always returns a language, so an empty value is the only way to show the options.
    vi.spyOn(LocaleService, 'resolveStartupLocale').mockReturnValue(detected as AppLocale);
    const fixture: ComponentFixture<LanguageSelectorPage> = TestBed.createComponent(LanguageSelectorPage);
    fixture.detectChanges();
    return fixture.nativeElement as HTMLElement;
  };

  const optionButtons = (page: HTMLElement): HTMLButtonElement[] => Array.from(page.querySelectorAll<HTMLButtonElement>('.language__lang'));

  beforeEach(async () => {
    localeService.changeLocale.mockReset();
    vi.useFakeTimers();

    await TestBed.configureTestingModule({
      imports: [LanguageSelectorPage],
      providers: [{ provide: LocaleService, useValue: localeService }],
    }).compileComponents();
  });

  afterEach(() => {
    vi.useRealTimers();
    vi.restoreAllMocks();
  });

  describe('when a language is detected', () => {
    it.each(['es', 'en', 'pt'])('redirects to %s after the delay and not before', (locale) => {
      createPage(locale);

      vi.advanceTimersByTime(REDIRECT_DELAY_MS - 1);
      expect(localeService.changeLocale).not.toHaveBeenCalled();

      vi.advanceTimersByTime(1);
      expect(localeService.changeLocale).toHaveBeenCalledTimes(1);
      expect(localeService.changeLocale).toHaveBeenCalledWith(locale);
    });

    it('shows the loading view and hides the language options while redirecting', () => {
      const page = createPage('es');

      expect(page.querySelector('app-loading-page')).toBeTruthy();
      expect(optionButtons(page)).toHaveLength(0);
      expect(page.querySelector('.language')?.classList.contains('language--redirecting')).toBe(true);
    });
  });

  describe('when no language is detected', () => {
    it('shows the options ES, EN and PT in that order', () => {
      const page = createPage('');

      const options = optionButtons(page).map((button) => [button.querySelector('strong')?.textContent, button.querySelector('span')?.textContent]);

      expect(options).toEqual([
        ['ES', 'Español'],
        ['EN', 'English'],
        ['PT', 'Português'],
      ]);
    });

    it('hides the loading view and does not redirect on its own', () => {
      const page = createPage('');

      vi.advanceTimersByTime(REDIRECT_DELAY_MS * 4);

      expect(page.querySelector('app-loading-page')).toBeFalsy();
      expect(page.querySelector('.language')?.classList.contains('language--redirecting')).toBe(false);
      expect(localeService.changeLocale).not.toHaveBeenCalled();
    });

    it.each([
      [0, 'es'],
      [1, 'en'],
      [2, 'pt'],
    ])('changes the language when option %s is clicked', (index, locale) => {
      const page = createPage('');

      optionButtons(page)[index].click();

      expect(localeService.changeLocale).toHaveBeenCalledTimes(1);
      expect(localeService.changeLocale).toHaveBeenCalledWith(locale);
    });

    it.each([
      [0, 'es'],
      [1, 'en'],
      [2, 'pt'],
    ])('changes the language when Enter is released on option %s', (index, locale) => {
      const page = createPage('');

      optionButtons(page)[index].dispatchEvent(new KeyboardEvent('keyup', { key: 'Enter' }));

      expect(localeService.changeLocale).toHaveBeenCalledTimes(1);
      expect(localeService.changeLocale).toHaveBeenCalledWith(locale);
    });

    it('ignores other keys released on an option', () => {
      const page = createPage('');

      optionButtons(page)[0].dispatchEvent(new KeyboardEvent('keyup', { key: 'a' }));

      expect(localeService.changeLocale).not.toHaveBeenCalled();
    });

    it.each([
      ['LinkedIn', 'www.linkedin.com'],
      ['GitHub', 'github.com'],
      ['npm', 'www.npmjs.com'],
    ])('has a %s link that opens %s in a new tab safely', (label, host) => {
      const page = createPage('');

      const link = Array.from(page.querySelectorAll<HTMLAnchorElement>('.language__channel')).find((anchor) => anchor.textContent?.includes(label));

      expect(new URL(link?.getAttribute('href') ?? '').hostname).toBe(host);
      expect(link?.getAttribute('target')).toBe('_blank');
      expect(link?.getAttribute('rel')).toContain('noopener');
    });
  });

  describe('with the real language detection', () => {
    it('redirects to the default language when nothing identifies the visitor, so the options never show', () => {
      vi.stubGlobal('navigator', { languages: [], language: '' });
      window.history.replaceState({}, '', '/');
      const fixture = TestBed.createComponent(LanguageSelectorPage);
      const page = fixture.nativeElement as HTMLElement;

      fixture.detectChanges();
      vi.advanceTimersByTime(REDIRECT_DELAY_MS);

      expect(localeService.changeLocale).toHaveBeenCalledWith('es');
      expect(optionButtons(page)).toHaveLength(0);
      vi.unstubAllGlobals();
    });
  });
});
